name: autofix.ci

on:
  pull_request:
  push:
    branches: [main, p-suite]
  schedule:
    - cron: '0 0 * * 0'

permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - run: pnpm install --no-frozen-lockfile
      - run: pnpm generate
      - name: autofix
        uses: autofix-ci/action@ff86a557419858bb967097bfc916833f5647fa8c
